### ISSUE TITLE
Suggestion: Think about building it for “scan once” so that libraries can be low-cost hosted on S3

### ISSUE THREAD

**Issue by Joshfindit** [DusteDdk/dstream#2]
For example:

I ran a trial of putting 300GB of music on S3
- I was charged 300GB of upload (understandable)
- Plex was installed to Digital Ocean with a mount to the S3 storage volume
- Plex went through and scanned the full content of all files, causing a charge of 300GB of egress (“Grumble grumble..Should have just scanned ID3 tags, but at least it’s done..grumble grumble”)
- No more music was was uploaded, and no files changed
- Plex *continued* to scan regularly causing multiple GB of egress charges *per day*

Since music files do not change (maybe we update the metadata, but that’s usually before it’s added to the library), they become great candidates for S3 (or other S3-compatible services such as B1) and if the app is built with those in mind, it becomes a game-changer.

For example:
- Pre-scan everything locally, grabbing all metadata
- Upload the scanned media, accepting that 300GB ingress charge
- Copy the scan results to a cloud server (or even multiple cloud servers for redundancy)
- Pay *nothing else* besides storage and egress of the music files themselves (Super cheap)
- Be happy and satisfied with all the power and flexibility for pennies

**Comment by DusteDdk** [comment]
Closing this, arguing that it is already scan-once when using docker volumes correctly, or when running without docker.

**Comment by Joshfindit** [comment]
Sorry for not replying to this earlier: That sounds like it would work exactly as I hope it would. I also consider this closed 🎉
